name: Validate PR on develop branch

on:
  pull_request:
    branches: [develop]
    paths:
      - 'BasicProject/force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Salesforce CLI (modern sf)
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version
          node -v

      # Install sfdx-git-delta with no prompts
      - name: Install sfdx-git-delta
        run: |
          sf plugins install sfdx-git-delta@latest --non-interactive
          sf plugins

      # Install SFDX Scanner with no prompts
      - name: Install SFDX Scanner
        run: |
          sf plugins install @salesforce/sfdx-scanner --non-interactive
          sf plugins

      # Authenticate to a normal org from the auth URL secret
      - name: Authenticate to Salesforce Org
        run: |
          echo '{ "sfdxAuthUrl": "'"${{ secrets.SFDX_DEVELOP_URL }}"'" }' > auth.json
          sf org login sfdx-url --sfdx-url-file auth.json --alias MyOrgAlias --set-default
          sf org display --target-org MyOrgAlias

      # Generate delta inside BasicProject (SFDX project folder)
      - name: Create delta package
        working-directory: BasicProject
        run: |
          mkdir -p delta
          sf sgd source delta \
            --to "HEAD" \
            --from "HEAD^" \
            --output delta \
            --generate-delta \
            --source force-app/

      # Validate deployment from inside BasicProject
      - name: Validate deployment
        working-directory: BasicProject
        run: |
          if [ -d "delta/force-app" ] && [ "$(ls -A delta/force-app 2>/dev/null)" ]; then
            sf project deploy start \
              --source-dir "delta/force-app" \
              --dry-run \
              --target-org MyOrgAlias
          else
            echo "No changes to deploy."
          fi
