name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli

      # 4. Install sfdx-git-delta plugin (non-interactive)
      - name: Install sfdx-git-delta
        run: |
          sfdx plugins:install sfdx-git-delta@latest --non-interactive

      # 5. Authenticate using auth URL
      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth_url.txt
          sfdx force:auth:sfdxurl:store --sfdxurlfile auth_url.txt --setalias MyOrg --setdefaultusername

      # 6. Change to the BasicProject directory (IMPORTANT)
      - name: Change to BasicProject
        run: cd BasicProject

      # 7. Create delta package
      - name: Create Delta Package
        working-directory: BasicProject
        run: |
          mkdir delta
          sfdx sgd:source:delta --from HEAD~1 --to HEAD --output delta/ --generate-delta

      # 8. Deploy to Salesforce
      - name: Deploy to Salesforce
        working-directory: BasicProject
        run: |
          sfdx force:source:deploy -p delta/ --testlevel NoTestRun
