name: Validate Salesforce Metadata

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Use Node.js 20 for everything after this point
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install Salesforce CLI (latest)
      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      # Step 4: Install sfdx-git-delta plugin
      - name: Install sfdx-git-delta
        run: sfdx plugins:install sfdx-git-delta@latest

      # Step 5: Authenticate to your normal Salesforce org
      - name: Authenticate to Salesforce Org
        run: |
          echo "${{ secrets.SFDX_DEVELOP_URL }}" > auth_url.txt
          sfdx auth:sfdxurl:store -f auth_url.txt -a MyOrgAlias
        # Store an auth URL from your org in the SFDX_AUTH_URL GitHub secret

      # Step 6: Create delta package
      - name: Create delta package
        run: |
          mkdir delta
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output delta --generate-delta

      # Step 7: Validate deployment in normal org
      - name: Validate deployment
        run: |
          sfdx force:source:deploy \
            --sourcepath delta \
            --targetusername MyOrgAlias \
            --checkonly \
            --testlevel RunLocalTests
